spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gwent}
    username: ${DB_USERNAME:gwent}
    password: ${DB_PASSWORD:gwent}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
